version: "2"

exclude_patterns:
- node_modules
- coverage
- dist
- documentation

plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
  stylelint:
      enabled: true
  scss-lint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
