window.esdocSearchIndex = [
  [
    "xbks/src/js/services/api-potier.js~apipotier",
    "class/src/js/services/api-potier.js~ApiPotier.html",
    "<span>ApiPotier</span> <span class=\"search-result-import-path\">xbks/src/js/services/api-potier.js</span>",
    "class"
  ],
  [
    "xbks/src/js/components/book-preview/book-preview.js~bookpreview",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html",
    "<span>BookPreview</span> <span class=\"search-result-import-path\">xbks/src/js/components/book-preview/book-preview.js</span>",
    "class"
  ],
  [
    "xbks/src/js/components/books-list/books-list.js~bookslist",
    "class/src/js/components/books-list/books-list.js~BooksList.html",
    "<span>BooksList</span> <span class=\"search-result-import-path\">xbks/src/js/components/books-list/books-list.js</span>",
    "class"
  ],
  [
    "xbks/src/js/components/cart/cart.js~cart",
    "class/src/js/components/cart/cart.js~Cart.html",
    "<span>Cart</span> <span class=\"search-result-import-path\">xbks/src/js/components/cart/cart.js</span>",
    "class"
  ],
  [
    "xbks/src/js/pages/home.js~home",
    "class/src/js/pages/home.js~Home.html",
    "<span>Home</span> <span class=\"search-result-import-path\">xbks/src/js/pages/home.js</span>",
    "class"
  ],
  [
    "xbks/src/js/layout.js~layout",
    "class/src/js/layout.js~Layout.html",
    "<span>Layout</span> <span class=\"search-result-import-path\">xbks/src/js/layout.js</span>",
    "class"
  ],
  [
    "xbks/src/js/utils.js~utils",
    "variable/index.html#static-variable-Utils",
    "<span>Utils</span> <span class=\"search-result-import-path\">xbks/src/js/utils.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/js/app-info.js",
    "file/src/js/app-info.js.html",
    "src/js/app-info.js",
    "file"
  ],
  [
    "src/js/components/book-preview/book-preview.js",
    "file/src/js/components/book-preview/book-preview.js.html",
    "src/js/components/book-preview/book-preview.js",
    "file"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#$toastcontent",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-member-$toastContent",
    "src/js/components/book-preview/book-preview.js~BookPreview#$toastContent",
    "member"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#addbutton",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-member-addButton",
    "src/js/components/book-preview/book-preview.js~BookPreview#addButton",
    "member"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#addcartlistener",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-member-addCartListener",
    "src/js/components/book-preview/book-preview.js~BookPreview#addCartListener",
    "member"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#cart",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-member-cart",
    "src/js/components/book-preview/book-preview.js~BookPreview#cart",
    "member"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#cartloader",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-member-cartLoader",
    "src/js/components/book-preview/book-preview.js~BookPreview#cartLoader",
    "member"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#constructor",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-constructor-constructor",
    "src/js/components/book-preview/book-preview.js~BookPreview#constructor",
    "method"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#data",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-member-data",
    "src/js/components/book-preview/book-preview.js~BookPreview#data",
    "member"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#destroy",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-method-destroy",
    "src/js/components/book-preview/book-preview.js~BookPreview#destroy",
    "method"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#el",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-member-el",
    "src/js/components/book-preview/book-preview.js~BookPreview#el",
    "member"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#onadd",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-method-onAdd",
    "src/js/components/book-preview/book-preview.js~BookPreview#onAdd",
    "method"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#onseecart",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-method-onSeeCart",
    "src/js/components/book-preview/book-preview.js~BookPreview#onSeeCart",
    "method"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#prepare",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-method-prepare",
    "src/js/components/book-preview/book-preview.js~BookPreview#prepare",
    "method"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#seecartlistener",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-member-seeCartListener",
    "src/js/components/book-preview/book-preview.js~BookPreview#seeCartListener",
    "member"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#toastbutton",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-member-toastButton",
    "src/js/components/book-preview/book-preview.js~BookPreview#toastButton",
    "member"
  ],
  [
    "src/js/components/book-preview/book-preview.js~bookpreview#toggleloadercartbutton",
    "class/src/js/components/book-preview/book-preview.js~BookPreview.html#instance-method-toggleLoaderCartButton",
    "src/js/components/book-preview/book-preview.js~BookPreview#toggleLoaderCartButton",
    "method"
  ],
  [
    "src/js/components/books-list/books-list.js",
    "file/src/js/components/books-list/books-list.js.html",
    "src/js/components/books-list/books-list.js",
    "file"
  ],
  [
    "src/js/components/books-list/books-list.js~bookslist#api",
    "class/src/js/components/books-list/books-list.js~BooksList.html#instance-member-api",
    "src/js/components/books-list/books-list.js~BooksList#api",
    "member"
  ],
  [
    "src/js/components/books-list/books-list.js~bookslist#constructor",
    "class/src/js/components/books-list/books-list.js~BooksList.html#instance-constructor-constructor",
    "src/js/components/books-list/books-list.js~BooksList#constructor",
    "method"
  ],
  [
    "src/js/components/books-list/books-list.js~bookslist#content",
    "class/src/js/components/books-list/books-list.js~BooksList.html#instance-member-content",
    "src/js/components/books-list/books-list.js~BooksList#content",
    "member"
  ],
  [
    "src/js/components/books-list/books-list.js~bookslist#data",
    "class/src/js/components/books-list/books-list.js~BooksList.html#instance-member-data",
    "src/js/components/books-list/books-list.js~BooksList#data",
    "member"
  ],
  [
    "src/js/components/books-list/books-list.js~bookslist#destroy",
    "class/src/js/components/books-list/books-list.js~BooksList.html#instance-method-destroy",
    "src/js/components/books-list/books-list.js~BooksList#destroy",
    "method"
  ],
  [
    "src/js/components/books-list/books-list.js~bookslist#display",
    "class/src/js/components/books-list/books-list.js~BooksList.html#instance-method-display",
    "src/js/components/books-list/books-list.js~BooksList#display",
    "method"
  ],
  [
    "src/js/components/books-list/books-list.js~bookslist#el",
    "class/src/js/components/books-list/books-list.js~BooksList.html#instance-member-el",
    "src/js/components/books-list/books-list.js~BooksList#el",
    "member"
  ],
  [
    "src/js/components/books-list/books-list.js~bookslist#init",
    "class/src/js/components/books-list/books-list.js~BooksList.html#instance-method-init",
    "src/js/components/books-list/books-list.js~BooksList#init",
    "method"
  ],
  [
    "src/js/components/books-list/books-list.js~bookslist#prepare",
    "class/src/js/components/books-list/books-list.js~BooksList.html#instance-method-prepare",
    "src/js/components/books-list/books-list.js~BooksList#prepare",
    "method"
  ],
  [
    "src/js/components/books-list/books-list.js~bookslist#previews",
    "class/src/js/components/books-list/books-list.js~BooksList.html#instance-member-previews",
    "src/js/components/books-list/books-list.js~BooksList#previews",
    "member"
  ],
  [
    "src/js/components/cart/cart.js",
    "file/src/js/components/cart/cart.js.html",
    "src/js/components/cart/cart.js",
    "file"
  ],
  [
    "src/js/components/cart/cart.js~cart#$modal",
    "class/src/js/components/cart/cart.js~Cart.html#instance-member-$modal",
    "src/js/components/cart/cart.js~Cart#$modal",
    "member"
  ],
  [
    "src/js/components/cart/cart.js~cart#addbook",
    "class/src/js/components/cart/cart.js~Cart.html#instance-method-addBook",
    "src/js/components/cart/cart.js~Cart#addBook",
    "method"
  ],
  [
    "src/js/components/cart/cart.js~cart#api",
    "class/src/js/components/cart/cart.js~Cart.html#instance-member-api",
    "src/js/components/cart/cart.js~Cart#api",
    "member"
  ],
  [
    "src/js/components/cart/cart.js~cart#constructor",
    "class/src/js/components/cart/cart.js~Cart.html#instance-constructor-constructor",
    "src/js/components/cart/cart.js~Cart#constructor",
    "method"
  ],
  [
    "src/js/components/cart/cart.js~cart#content",
    "class/src/js/components/cart/cart.js~Cart.html#instance-member-content",
    "src/js/components/cart/cart.js~Cart#content",
    "member"
  ],
  [
    "src/js/components/cart/cart.js~cart#discount",
    "class/src/js/components/cart/cart.js~Cart.html#instance-member-discount",
    "src/js/components/cart/cart.js~Cart#discount",
    "member"
  ],
  [
    "src/js/components/cart/cart.js~cart#el",
    "class/src/js/components/cart/cart.js~Cart.html#instance-member-el",
    "src/js/components/cart/cart.js~Cart#el",
    "member"
  ],
  [
    "src/js/components/cart/cart.js~cart#findbestreduction",
    "class/src/js/components/cart/cart.js~Cart.html#instance-method-findBestReduction",
    "src/js/components/cart/cart.js~Cart#findBestReduction",
    "method"
  ],
  [
    "src/js/components/cart/cart.js~cart#findoffers",
    "class/src/js/components/cart/cart.js~Cart.html#instance-method-findOffers",
    "src/js/components/cart/cart.js~Cart#findOffers",
    "method"
  ],
  [
    "src/js/components/cart/cart.js~cart#init",
    "class/src/js/components/cart/cart.js~Cart.html#instance-method-init",
    "src/js/components/cart/cart.js~Cart#init",
    "method"
  ],
  [
    "src/js/components/cart/cart.js~cart#initmodal",
    "class/src/js/components/cart/cart.js~Cart.html#instance-method-initModal",
    "src/js/components/cart/cart.js~Cart#initModal",
    "method"
  ],
  [
    "src/js/components/cart/cart.js~cart#items",
    "class/src/js/components/cart/cart.js~Cart.html#instance-member-items",
    "src/js/components/cart/cart.js~Cart#items",
    "member"
  ],
  [
    "src/js/components/cart/cart.js~cart#layout",
    "class/src/js/components/cart/cart.js~Cart.html#instance-member-layout",
    "src/js/components/cart/cart.js~Cart#layout",
    "member"
  ],
  [
    "src/js/components/cart/cart.js~cart#offers",
    "class/src/js/components/cart/cart.js~Cart.html#instance-member-offers",
    "src/js/components/cart/cart.js~Cart#offers",
    "member"
  ],
  [
    "src/js/components/cart/cart.js~cart#onopencart",
    "class/src/js/components/cart/cart.js~Cart.html#instance-method-onOpenCart",
    "src/js/components/cart/cart.js~Cart#onOpenCart",
    "method"
  ],
  [
    "src/js/components/cart/cart.js~cart#render",
    "class/src/js/components/cart/cart.js~Cart.html#instance-method-render",
    "src/js/components/cart/cart.js~Cart#render",
    "method"
  ],
  [
    "src/js/components/cart/cart.js~cart#subtotal",
    "class/src/js/components/cart/cart.js~Cart.html#instance-member-subTotal",
    "src/js/components/cart/cart.js~Cart#subTotal",
    "member"
  ],
  [
    "src/js/components/cart/cart.js~cart#totalorder",
    "class/src/js/components/cart/cart.js~Cart.html#instance-member-totalOrder",
    "src/js/components/cart/cart.js~Cart#totalOrder",
    "member"
  ],
  [
    "src/js/components/cart/cart.js~cart#updatediscount",
    "class/src/js/components/cart/cart.js~Cart.html#instance-method-updateDiscount",
    "src/js/components/cart/cart.js~Cart#updateDiscount",
    "method"
  ],
  [
    "src/js/components/cart/cart.js~cart#updatesubtotal",
    "class/src/js/components/cart/cart.js~Cart.html#instance-method-updateSubTotal",
    "src/js/components/cart/cart.js~Cart#updateSubTotal",
    "method"
  ],
  [
    "src/js/components/cart/cart.js~cart#updatetotals",
    "class/src/js/components/cart/cart.js~Cart.html#instance-method-updateTotals",
    "src/js/components/cart/cart.js~Cart#updateTotals",
    "method"
  ],
  [
    "src/js/layout.js",
    "file/src/js/layout.js.html",
    "src/js/layout.js",
    "file"
  ],
  [
    "src/js/layout.js~layout#buttonslistener",
    "class/src/js/layout.js~Layout.html#instance-member-buttonsListener",
    "src/js/layout.js~Layout#buttonsListener",
    "member"
  ],
  [
    "src/js/layout.js~layout#constructor",
    "class/src/js/layout.js~Layout.html#instance-constructor-constructor",
    "src/js/layout.js~Layout#constructor",
    "method"
  ],
  [
    "src/js/layout.js~layout#createmainloader",
    "class/src/js/layout.js~Layout.html#instance-method-createMainLoader",
    "src/js/layout.js~Layout#createMainLoader",
    "method"
  ],
  [
    "src/js/layout.js~layout#displaymainloader",
    "class/src/js/layout.js~Layout.html#instance-method-displayMainLoader",
    "src/js/layout.js~Layout#displayMainLoader",
    "method"
  ],
  [
    "src/js/layout.js~layout#init",
    "class/src/js/layout.js~Layout.html#instance-method-init",
    "src/js/layout.js~Layout#init",
    "method"
  ],
  [
    "src/js/layout.js~layout#initmenu",
    "class/src/js/layout.js~Layout.html#instance-method-initMenu",
    "src/js/layout.js~Layout#initMenu",
    "method"
  ],
  [
    "src/js/layout.js~layout#listenmenu",
    "class/src/js/layout.js~Layout.html#instance-method-listenMenu",
    "src/js/layout.js~Layout#listenMenu",
    "method"
  ],
  [
    "src/js/layout.js~layout#loader",
    "class/src/js/layout.js~Layout.html#instance-member-loader",
    "src/js/layout.js~Layout#loader",
    "member"
  ],
  [
    "src/js/layout.js~layout#menubuttons",
    "class/src/js/layout.js~Layout.html#instance-member-menuButtons",
    "src/js/layout.js~Layout#menuButtons",
    "member"
  ],
  [
    "src/js/layout.js~layout#onmenuitem",
    "class/src/js/layout.js~Layout.html#instance-method-onMenuItem",
    "src/js/layout.js~Layout#onMenuItem",
    "method"
  ],
  [
    "src/js/layout.js~layout#removemainloader",
    "class/src/js/layout.js~Layout.html#instance-method-removeMainLoader",
    "src/js/layout.js~Layout#removeMainLoader",
    "method"
  ],
  [
    "src/js/main.js",
    "file/src/js/main.js.html",
    "src/js/main.js",
    "file"
  ],
  [
    "src/js/pages/home.js",
    "file/src/js/pages/home.js.html",
    "src/js/pages/home.js",
    "file"
  ],
  [
    "src/js/pages/home.js~home#booklist",
    "class/src/js/pages/home.js~Home.html#instance-member-bookList",
    "src/js/pages/home.js~Home#bookList",
    "member"
  ],
  [
    "src/js/pages/home.js~home#books",
    "class/src/js/pages/home.js~Home.html#instance-member-books",
    "src/js/pages/home.js~Home#books",
    "member"
  ],
  [
    "src/js/pages/home.js~home#cart",
    "class/src/js/pages/home.js~Home.html#instance-member-cart",
    "src/js/pages/home.js~Home#cart",
    "member"
  ],
  [
    "src/js/pages/home.js~home#constructor",
    "class/src/js/pages/home.js~Home.html#instance-constructor-constructor",
    "src/js/pages/home.js~Home#constructor",
    "method"
  ],
  [
    "src/js/pages/home.js~home#el",
    "class/src/js/pages/home.js~Home.html#instance-member-el",
    "src/js/pages/home.js~Home#el",
    "member"
  ],
  [
    "src/js/pages/home.js~home#layout",
    "class/src/js/pages/home.js~Home.html#instance-member-layout",
    "src/js/pages/home.js~Home#layout",
    "member"
  ],
  [
    "src/js/pages/home.js~home#runapp",
    "class/src/js/pages/home.js~Home.html#instance-method-runApp",
    "src/js/pages/home.js~Home#runApp",
    "method"
  ],
  [
    "src/js/pages/home.js~home#showpage",
    "class/src/js/pages/home.js~Home.html#instance-method-showPage",
    "src/js/pages/home.js~Home#showPage",
    "method"
  ],
  [
    "src/js/services/api-potier.js",
    "file/src/js/services/api-potier.js.html",
    "src/js/services/api-potier.js",
    "file"
  ],
  [
    "src/js/services/api-potier.js~apipotier#constructor",
    "class/src/js/services/api-potier.js~ApiPotier.html#instance-constructor-constructor",
    "src/js/services/api-potier.js~ApiPotier#constructor",
    "method"
  ],
  [
    "src/js/services/api-potier.js~apipotier#getallbooks",
    "class/src/js/services/api-potier.js~ApiPotier.html#instance-method-getAllBooks",
    "src/js/services/api-potier.js~ApiPotier#getAllBooks",
    "method"
  ],
  [
    "src/js/services/api-potier.js~apipotier#getoffers",
    "class/src/js/services/api-potier.js~ApiPotier.html#instance-method-getOffers",
    "src/js/services/api-potier.js~ApiPotier#getOffers",
    "method"
  ],
  [
    "src/js/services/api-potier.js~apipotier#urlallbooks",
    "class/src/js/services/api-potier.js~ApiPotier.html#instance-member-urlAllBooks",
    "src/js/services/api-potier.js~ApiPotier#urlAllBooks",
    "member"
  ],
  [
    "src/js/utils.js",
    "file/src/js/utils.js.html",
    "src/js/utils.js",
    "file"
  ]
]